name: Gestionar Issues

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

on:
  issues:
    types: [opened, labeled]

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Gestion de issues y proyecto
    steps:
      - name: Etiquetar pendiente
        uses: andymckay/labeler@master
        if: github.event.action == 'opened'
        with:
          add-labels: "pendiente"
      

      - name: Asignar a Columna Pendiente de Revision
        uses: srggrs/assign-one-project-github-action@1.2.1
        if: |
          contains(github.event.issue.labels.*.name, 'pendiente') ||
          github.event.action == 'opened'
        with:
          project: 'https://github.com/mdmontesinos/GitHubActions/projects/1'
          column_name: 'Pendiente de Revisión'

      - name: Asignar a Columna Aprobado
        uses: srggrs/assign-one-project-github-action@1.2.1
        if: contains(github.event.issue.labels.*.name, 'aprobado')
        with:
          project: 'https://github.com/mdmontesinos/GitHubActions/projects/1'
          column_name: 'Aprobado'

      - name: Asignar a Columna En Desarrollo
        uses: srggrs/assign-one-project-github-action@1.2.1
        if: contains(github.event.issue.labels.*.name, 'en-desarrollo')
        with:
          project: 'https://github.com/mdmontesinos/GitHubActions/projects/1'
          column_name: 'En Desarrollo'

      - name: Asignar a Columna Completado
        uses: srggrs/assign-one-project-github-action@1.2.1
        if: contains(github.event.issue.labels.*.name, 'completado')
        with:
          project: 'https://github.com/mdmontesinos/GitHubActions/projects/1'
          column_name: 'Completado'
