name: Construccion, Pruebas y Despliegue

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Configurar JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Construccion con Maven
      run: mvn -f pom.xml clean package verify javadoc:javadoc site:site
      
    - name: Copiar archivo index.html
      run: cp index.html target/
      
    - name: Generacion de artefactos
      uses: actions/upload-artifact@v3
      with:
        name: GitHubActions-site
        path: '${{ github.workspace }}/target/*'
        
  despliegue:
  
    runs-on: ubuntu-latest
    
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: GitHubActions-site

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@0b651ed7546ecfc75024011f76944cb9b381ef1e
        with:
          app-name: hmis-githubactions
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
    
      
