name: Construccion, Pruebas y Despliegue

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Configurar JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Construccion con Maven
      run: mvn -f pom.xml clean package verify javadoc:javadoc site:site
      
    - name: Generacion de artefactos
      uses: actions/upload-artifact@v3
      with:
        name: GitHubActions
        path: '${{ github.workspace }}/target/*'
        
  despliegue:
  
    runs-on: ubuntu-latest
    
    needs: build
    
    steps:
    - name: Desplegar Javadoc
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        token: ${{ secrets.HMIS }}
        branch: javadoc
        folder: .
    
      
