name: Issue movido de Columna

on:
  project_card:
    types:
      - moved
jobs:
  Reabrir:
    if: github.event.project_card.column_id != '18785978'
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/issue-states@v2
        with:
          github-token: ${{ secrets.TOKEN_GITHUB }}
          open-issue-columns: 'Pendiente de Revisión, Aprobado, En Desarrollo'

  Reetiquetar:
    runs-on: ubuntu-latest
    needs: Reabrir
    steps:
      - name: pendiente
        uses: andymckay/labeler@1.0.4
        if: github.event.project_card.column_id == '18785974'
        with:
          remove-labels: "aprobado, en-desarrollo, completado"
          add-labels: "pendiente"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: aprobado
        uses: andymckay/labeler@1.0.4
        if: github.event.project_card.column_id == '18785975'
        with:
          remove-labels: "pendiente, en-desarrollo, completado"
          add-labels: "aprobado"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: en-desarrollo
        uses: andymckay/labeler@1.0.4
        if: github.event.project_card.column_id == '18785977'
        with:
          remove-labels: "pendiente, aprobado, completado"
          add-labels: "en-desarrollo"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: completado
        uses: andymckay/labeler@1.0.4
        if: github.event.project_card.column_id == '18785978'
        with:
          remove-labels: "pendiente, aprobado, en-desarrollo"
          add-labels: "completado"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  
  Cerrar_Reabrir:
    if: github.event.project_card.column_id == '18785978'
    runs-on: ubuntu-latest
    needs: Reetiquetar
    steps:
      - uses: dessant/issue-states@v2
        with:
          github-token: ${{ secrets.TOKEN_GITHUB }}
          closed-issue-columns: 'Completado'
